name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/api-rate-limiter-gateway" ]; then
              git clone https://github.com/prajwal1014/api-rate-limiter-gateway.git /home/ubuntu/api-rate-limiter-gateway
            fi
            bash /home/ubuntu/api-rate-limiter-gateway/deploy.sh
